### ISSUE TITLE
Entities won't reappear if they are deleted

### ISSUE THREAD

**Issue by vbucuroiu** [sensu/web#328] opened 2020-07-14 12:47 UTC
I've deleted the entities in Sensu web and they don't reappear

## Expected Behavior
If I delete an entity, it should reappear at next keepalive check.
It only appears in "Events" but not in "Entities".
However, I can see the entity with sensuctl

## Steps to Reproduce
1. Delete entity from Sensu web
2. Wait for next keepalive
3. Restart sensu-agent
4. The entity never reappears in Sensu Web

## Your Environment
* Sensu-go-agent/backend/cli 5.21.0 (community edition)
* Sensu web 1.0.1 (community edition)
* Installation method: sources
* Operating System: Ubuntu 18.04
* Browser used: Firefox

**Comment by portertech** [comment] 2020-07-14 18:11
Unable to reproduce this issue with a commercial build, using the steps above. Can you reproduce the issue using the commercial web ui? Closing this issue. If you continue to use your oss build and this issue persists, please file an issue at: https://github.com/sensu/web/issues

**Closed by portertech** 2020-07-14 18:11 UTC
Labels: issue: bug
